name = "xo-drops"
compatibility_date = "2025-07-08"
account_id = "${CF_ACCOUNT_ID}"  # Renamed and sourced via GitHub secret or environment
workers_dev = false

[build]
command = "echo 'XO Drops – no build needed'"
upload.format = "directory"
upload.dir = "drops/brie_scroll"

[env.production]
account_id = "${CF_ACCOUNT_ID}"
vars = { PULSE_SECRET = "${PULSE_SECRET}" }

[env.preview]
account_id = "${CF_ACCOUNT_ID}"
vars = { PULSE_SECRET = "${PULSE_SECRET}" }
upload.dir = "drops/eighth_seal"