name = "xo-drops"
compatibility_date = "2025-07-08"
account_id = "${CF_ACCOUNT_ID}"  # Sourced via CLOUDFLARE_API_TOKEN environment variable
workers_dev = false

[build]
command = "echo 'XO Drops – no build needed'"
directory = "drops/landing"

[env.production]
account_id = "${CF_ACCOUNT_ID}"
vars = { PULSE_SECRET = "${PULSE_SECRET}" }

[env.preview]
account_id = "${CF_ACCOUNT_ID}"
vars = { PULSE_SECRET = "${PULSE_SECRET}" }
directory = "drops/eighth_seal"

[[redirects]]
from = "/"
to = "/drops/landing/"
status = 302