name = "xo-drops"
compatibility_date = "2025-07-08"
pages_build_output_dir = "./drops/landing"

[env.production]
vars = { PULSE_SECRET = "${PULSE_SECRET}" }

[env.preview]
vars = { PULSE_SECRET = "${PULSE_SECRET}" }