name = "xo-drops"
compatibility_date = "2025-07-08"
account_id = "your_account_id"  # Replace with actual Cloudflare Account ID
workers_dev = false

[build]
command = "echo 'XO Drops – no build needed'"
upload.format = "directory"
upload.dir = "drops/brie_scroll"

[env.production]
vars = { PULSE_SECRET = "your_pulse_secret_here" }  # Replace with your real secret or use wrangler secret